- name: hth | symlink | create destination directory
  ansible.builtin.file:
    path: "{{ link.destination.path }}"
    state: directory
    owner: "{{ link.destination.owner }}"
    group: "{{ link.destination.group }}"
    modification_time: preserve
    access_time: preserve
    mode: "{{ link.destination.mode }}"
  when:
    - link.destination.make is defined
    - link.destination.make

- name: hth | symlink | stat location
  ansible.builtin.stat:
    path: "{{ link.location.path }}"
  register: destination

- name: hth | symlink | remove location
  ansible.builtin.file:
    path: "{{ link.location.path }}"
    state: absent
  when:
    - link.location.force is defined
    - link.location.force
    - destination.stat.exists
    - destination.stat.isdir or (destination.stat.islnk and destination.stat.lnk_source != "{{ link.destination.path }}")

- name: hth | symlink | create link
  ansible.builtin.file:
    src: "{{ link.destination.path }}"
    dest: "{{ link.location.path }}"
    state: link
    owner: "{{ link.location.owner }}"
    group: "{{ link.location.group }}"
    modification_time: preserve
    access_time: preserve
